# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(180, 240, 220, 80))
        self.btn.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.btn.setObjectName("btn")
        self.close_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(10, 542, 181, 51))
        self.close_btn.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.close_btn.setObjectName("close_btn")
        self.fon = QtWidgets.QLabel(parent=self.centralwidget)
        self.fon.setGeometry(QtCore.QRect(-320, -100, 1071, 861))
        self.fon.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0))")
        self.fon.setObjectName("fon")
        self.fon.raise_()
        self.btn.raise_()
        self.close_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn.setText(_translate("MainWindow", "Создать/изменить \n"
"данные о кофе"))
        self.close_btn.setText(_translate("MainWindow", "Закрыть \n"
"приложение"))
        self.fon.setText(_translate("MainWindow", "TextLabel"))
